# -*- mode: org; fill-column: 79; -*-

#+TITLE: Outline of /The Elements of User Experience/
#+SUBTITLE: User-Centered Design for the Web and Beyond (2nd Edition)
#+AUTHOR: Jesse James Garrett
#+CREATOR: WLHarvey4
#+DATE: <2019-02-02 Sat 22:42>

#+TEXINFO: @insertcopying

* Introduction
  :PROPERTIES:
  :UNNUMBERED: t
  :END:

** About the Author

   {{{AUTHOR}}}:
   - Is a founder of Adaptive Path, a user experience consultancy based in S.F.;
   - Has made contributions to the field of user experience include the Visual
     Vocabulary, an open notation system for information architecture
     documentation;
   - Has a personal web site at [[http://www.jjg.net]], is one of the world's most
     popular destinations for information architecture resources;

** To the Second Edition

   This book is no longer just about web sites.  Overall, the themes, concepts,
   and principles apply to products and services of all kinds.

   The field of user experience has broadened its horizons.  Practitioners now
   regularly talk about the impact and value of user experience design in areas
   far beyond the limited context of the Web or even screen-based interactive
   applications that dominated the conversation back when this book was first
   written.

   The Web is still central to the book, if only to acknowledge the model's
   roots in that medium.  But this book doesn't require an insider's knowledge
   of how Web development happens---so even if you don't create Web sites, you
   should be able to see how to apply these ideas in your own work.

** To the First Edition

   This is not a how-to book.  There are many books out there that explain how
   Web sites get made.  This is not one of them.

   This is not a book about technology.  There is not a single line of code to
   be found between these covers.

   This is not a book of answers.  Instead, this book is about asking the right
   questions.

   This book will tell you what you need to know before you go read those other
   books.  If you need the big picture, if you need to understand the context
   for the decisions that user experience practitioners make, this book is for
   you.

   This book is designed to be read easily in just a few hours.  If you're a
   newcomer to the world of user experience, this book will give you the
   foundation you need.  If you're already familiar with the methods and
   concerns of the field of user experience, this book will help you
   communicate them  more effectively to the people you work with.

* User Experience and Why It Matters

  Products and services are made by people and someone, somewhere should get
  the credit when they work well for us---or get the blame when they don't.

** Everyday Miseries

   Everyone, every once in a while, has one of those days.

   ...

** Introducing User Experience

   - The accident
   - The register
   - The pump
   - The coffeemaker
   - The Clock


   #+cindex: user experience, introduction
   In short, every one of the previous cases of ``bad luck'' could have been
   avoided had someone made different choices in designing a product or
   service.  These examples all demonstrate a lack of attention to the *user
   experience*:  the experience the product creates for the people who use it
   in the real world.  When a product is being developed, people pay a great
   deal of attention to what it does.  User experience is the other, often
   overlooked, side of the equation---how it works---that can often make the
   difference between a successful product and a failure.

   User experience is not about the inner workings of a product or service.
   User experience is about how it works on the outside, where a person comes
   into contact with it.  When someone asks you what it's like to use a product
   or service, they're asking about the user experience.  Is it hard to do
   simple things?  Is it easy to figure out?  How does it feel to interact with
   the product?

   That interaction often involves pushing a lot of buttons, as in the case of
   technology products such as alarm clocks, coffeemakers, or cash registers.
   Sometimes its just a matter of simply physical mechanism, such as the gas
   cap on your car.  However, every product that is used by someone creates a
   user experience: books, ketchup bottles, reclining armchairs, cardigan
   sweaters.

   For any kind of product or service, its the little things that count.
   Having a button click when you push it down doesn't seem like much, but when
   that click makes the difference between getting coffee and not getting
   coffee, it matters a great deal.  Even if you never realized that the design
   of that button was causing you trouble, how would you feel about a
   coffeemaker that you were able to use successfully only party of the time?
   How would you feel about the manufacturer?  Would you buy another product
   from that company in the future?  Probably not.  Thus, for want of a button
   that clicks, a customer is lost.

** From Product Design to User Experience Design

   #+cindex: aesthetic appeal
   #+cindex: product design
   When most people think about product design, they often think of it in terms
   of aesthetic appeal: a well-designed product is one that looks good to the
   eye and feels good to the touch.  Whether it's the curve of a sports car's
   body or the texture of a power drill's grip, the aesthetic dimension of
   product design is a sure attention-grabber.

   #+cindex: functional design
   Another common way people think about product design is in functional terms:
   A well-designed product is one that does what it promises to do.  And a
   badly-designed product is one that somehow doesn't: scissors that don't cut
   even though the blades are sharp, a pen that doesn't write even though it's
   full of ink, a printer that constantly jams.

   All of these can certainly be failures of design.  These products might look
   great and work well functionally, but designing products with the user
   experience as an explicit oucome means looking beyond the functional or
   aesthetic.

   #+cindex; product development
   Some people responsible for creating products may not think in terms of
   design at all.  For them, the process of creating a product is about
   development: steadily builidng up and refining the features and
   functionalities of the product until they add up to something viable to the
   marketplace.

   #+cindex: form follows function
   #+cindex: user-facing
   #+cindex: psychology
   #+cindex: behavior
   In this view, the design of a product is dictated by its functionality---or,
   as designers sometimes put it, ``form follows function.''  This approach
   makes complete sense for the inner workings of a product, the parts
   concealed from a user.  But when it comes to teh parts of a product that are
   user-facing---the buttons, displays, labels, and so forth---the ``correct''
   form isn't dictated by functionality at all.  Instead, its dictated by the
   psychology and behavior of the users themselves.

   #+cindex: context
   #+cindex: user experience design questions
   User experience design often deals with questions of context.  Aesthetic
   design makes ure the button on the coffeemaker is an appealing shape and
   texture.  Functional design makes sure it triggers the appropriate action on
   the device.  User experience design makes sure the aesthetic and functional
   aspects of the button work in the context of the rest of the product, asking
   questions like, ``Is the button too small for such an important function?''
   User experience design also makes sure the button works in the context of
   what the user is trying to accomplish, asking such quesstions like, ``Is the
   button in the right place relative to the other controls the user would be
   using at the same time?''

** Designing (for) Experience---Use Matters

   #+cindex: design, product vs user experience
   What's the difference between desigining a product and designing a user
   experience?  After all, every product intended for humans has a user, and
   every time a product is used, it delivers an experience.  The product can
   fail to deliver a satisfactory experience.

   #+cindex: simple cases, user experience built-in
   Manufacturers tend not to employ user experience designers.  In simple
   cases, the requirements to deliver a successful user experience are built
   into the definition of the product itself.

   #+cindex: complex products, user experience independent
   With more complex products, the requirements to deliver a successful user
   experience are independent of the definition of the product.

   #+cindex: user experience design, complex products
   And the more complex a product is, the more difficult it becomes to identify
   exactly how to deliver a successful experience to the user.  Each additional
   feature, function, or step in the process of using a product creates another
   opportunity for the experience to fall short.  As a result, the process of
   creating a successful product has to be quite different.  That's where
   product design has to be supported by user experience design.

** User Experience and the Web

   #+cindex: Web site as product
   User experience is vital to all kinds of products and services.  This book
   is primarily about the user experience of one particular kind of product:
   Web sites.  (/Site/ here refers to both content-oriented Web products and
   interactive Web applications.)

   #+cindex: Web site user experience
   #+cindex: user experience, Web site
   On the Web, user experience becomes even more important than it is for other
   kinds of products.  The lessons we've learned from creating user experience
   on the Web can be applied far beyond its boundaries.

   #+cindex: user experience, feeling stupid
   Web sites are complicated pieces of technology, and something funny happens
   when people have trouble using complicated pieces of technology: They blame
   themselves.  They feel like they must have done something wrong.  They feel
   like they weren't paying enough attention.  They feel stupid.  Sure, it's
   irrational.  After all, it's not their fault the site doesn't work the wey
   they expect it to.  But they feel stupid anyway.  And if you intend to drive
   people away from your site, it's hard to imagine a more effective approach
   than making them feel stupid when they use it.

   #+cindex: self-service product, Web site
   #+cindex: Web site, self-service product
   Regardless of the type of site, in virtually every case, a Web site is a
   self-service product.  There is no instruction manual to read beforehand, no
   training seminar to attend, no customer service representative to help guide
   the user through the site.  There is only the user, facing the site alone
   with only her wits and personal experience to guide her.

   #+cindex: acknowledge user experience
   It's bad enough that she's been stuck in the position of having to figure
   out the site on her own.  The fact that most sites don't even acknowledge
   her helpless condition only makes matters worse.,  Despite the vital
   strategic importance of user experience to the success of a Web site, the
   simple matter of understanding what people want and need has been a low
   priority for most of the history of the medium.

   #+cindex: user experience, neglected
   If user experience is such a vital part of any Web site, why is it so often
   neglected in the development process?  Many Web sites are built with the
   idea that being first to market is the key to success,.  In the earliest
   days of the Web, sites like Yahoo! built early leads that later competitors
   struggled to overcome.  Established companies raced to set up Web sites,
   determined not to be perceived as falling behind the times.  But in most
   cases, companies considered merelly having deployed the site a great
   accomplishment; whether the site actually worked for people was, at best, an
   afterthought.

   #+cindex: content and functionality glut
   #+cindex: more features
   To gain market share against these first-movers, competitors often add more
   and more content and functionality in hopes of drawing in new customers.
   This race to cram more features into products is hardly unique to the Web.

   Having more features, however, turns out to be only a temporary source of
   competitive advantage.  With the added complexity that comes with
   ever-expanding feature set, sites become increasingly unwieldy, hard to use,
   and unappealing to the very first-timers they are supposed to draw in.  And
   still, many organizations pay little attention to what users like, find
   valuable, or are really able to use.

   #+cindex: quality user experience
   More and more businesses have now come to recognize that providing a quality
   user experience is an essential, sustainable competitive advantage.  It is
   user experience that forms the customer's impression of a company's
   offerings; it is user experience that differentiates a company from its
   competitors; and it is user experience that determines whether your customer
   will ever come back.

** Good User Exerience is Good Business

   #+cindex: content, information
   #+cindex: informationm, content
   #+cindex; effective communication
   If your site consists of what Web pros call /content/---that is,
   information---then one of the main goals of your site is to communicate that
   information as effectively as possible.  It's not enough just to put it out
   there.  It has be presented in a way that helps people absorb it and
   understand it.  Otherwise, the user might not ever find out that you offer
   the service or product they're looking for.  And even if they do manage to
   find that information they're likely to draw the conclusion that if your
   site is difficult to work with, your company probably is as well.

   #+cindex: Web application
   If your site is a Web-based application that people can use to accomplish
   certain task, effective communication is a key factor in the success of your
   product.  The world's most powerful functionality falters and fails if users
   can't figure out how to make it work.

   #+cindex: loyalty
   Simply put, if your users have a bad experience, they won't come back.  If
   they have an OK experience with your site but a better experience with your
   competitor's site, they'll go back to that competitor, not you.  Features
   and functions always matter, but user experience has a far greater effect on
   customer loyalty.  All of your sophisticated technology and brand messaging
   won't bring those customers back a second time.  A good user experience
   will---and you don't get much of a second chance to get it right.

   #+cindex: return on investment
   #+cindex: ROI
   #+cindex: value for company
   Customer loyalty isn't the only way that focusing on the user experience of
   your site can pay off.  Businesses with an eye on the bottom line want to
   know about the *return on investment*, or *ROI*.  ROI is usually measured in
   terms of money: For every dollar you spend, how many dollars of value are
   you getting back?  That's the ROI.  But return on investment does not have
   to be expressed in strictly monetary terms.  All you need is a measurement
   that shows that your money going out translates into value for your company.

   #+cindex: conversion rate, ROI
   One common measure of return on investment is *conversion rate*.  Any time
   you want to encourage your customers to take the next step in building a
   relationship with you---whether that involves something as complex as
   customizing the site to their preferences or as simple as signing up to
   receive an e-mail newsletter---there's a conversion rate you can measure.
   By keeping track of what percentage of users you convert to the next level,
   you can measure how effectively your site is meeting your business goals.

   #+cindex: efficiency, increase
   #+cindexz; work faster
   #+cindex: mistakes, make fewer
   Any user experience effoert aims to increase efficiency.  This comes in two
   key forms: helping people work faster and helping them make fewer mistakes.
   Improving the efficiency of the tools you use improves the productivity of
   the business as a whole.  The less time it takes to complete any given task,
   the more you can get done in a day.  In keeping with the old notion that
   time is money, saving your employees time translates direclty into saving
   your business money.

   People like their jobs more when their tools are natural and easy to use,
   not frustrating and needlessly complex.

** Minding Your Users

   {{{heading(User-Centered Design)}}}
   #+cindex: user-centered design
   The practice of creating engaging, efficient user experience is called
   *user-centered design*.  The concept of user-centered design is very simple:
   Take the user into account every step of the way as you develop your
   product.  The implications of this simple concept are surprisinly complex.

   #+cindex: decisions, consciously made
   Everything the user experiences should be the result of a conscious decision
   on your part.  Realistically, you might have to make a compromise here and
   there because of the time or expense involved in creating a better
   solution.  But a user-centered design process ensures that those compromises
   don't happen by accident.  By thinking about the user experience, breaking
   it down into its component elements, and looking at it from several
   perspectives, you can ensure that you know all the ramifications of your
   decisions.

   The biggest reason user experience should matter to you is that it matters
   to your users.  if you don't provide them with a positive experience, they
   won't use your product.  And without users, all you've got is a dusty Web
   serverr somewhere, idly waiting to fulfill a request that will never come.
   For the users who do come, you must set out to provide them with an
   experience that is cohesive, intuitive, and maybe even pleasurable---an
   experience in which everything works the way it should.
* Meet the Elements

  #+CINDEX:user experience design process
  #+CINDEX:design process, conscious effort
  #+CINDEX:user expectations, understanding
  The user experience design process is all about ensuring that no aspect of
  the user's experience with your product happens without your conscious,
  explicit intent.  This means taking into account every possibility of every
  action the user is likely to take and understanding the user's expectations
  at every step of the way through that process.

  #+CINDEX:user experience, component elements
  By breaking the job of crafting user experience down into its component
  elements, we can better understand the task as a whole.

** The Five Planes

   #+CINDEX:planes, five
   Purchasing a physical product over the Web.  The experience is the same
   every time:

   - go to the site
   - find the item (search engine or browsing a catalog)
   - give your credit card number, address
   - site confirms that the product will be shipped to you


   #+CINDEX:decisions affect user experience
   #+CINDEX:user experience, design decisions affecting
   That neat, tidy experience actually results from a whole set of
   decisions---some small, some large---about how the site looks, how it
   behaves, and what it allows you to do.  These decisions build upon each
   other, informing and invluencing all aspects of the user experience.

   #+CINDEX:user experience, layers
   If we peel away the layers of that experience, we can begin to understand
   how those decisions are made.

*** The Surface Plane

    #+CINDEX:surface plane
    #+CINDEX:plane, surface
    On the *surface* you see a series of Web pages, made up of images and
    text.  Some of these images are things you can click on, performing some
    sort of function such as taking you to a shopping cart.  Some of these
    images are just illustrations, such as a photograph of a product for sale
    or the logo of the site itself.

*** The Skeleton Plane

    #+CINDEX:skeleton plane
    #+CINDEX:plane, skeleton
    Beneath that surface is the *skeleton* of the site: the placement of
    buttons, controls, photos, and blocks of text.  The skeleton is designed to
    optimize the arrangement of these elements for maximum effet and
    efficiency---so that you remember the logo and can find that shopping cart
    button when you need it.

*** The Structure Plane

    #+CINDEX:structure plane
    #+CINDEX:plane, structure
    The skeleton is a concrete expression of the more abstract *structure* of
    the site.  The skeleton might define the placement of the interface
    elements on our checkout page; the structure would define how users got to
    that page and where they could go when they were finished there.  The
    skeleton might define the arrangement of navigational elements allowing the
    users to browse categories of products; the structure would define what
    those categories were.

*** The Scope Plane

    #+CINDEX:scope plane
    #+CINDEX:plane, scope
    The structure defines the way in which the various features and functions
    of the site fit together.  Just what those features and functions
    are constitutes the *scope* of the site.  For example, some commerce sites
    offer a feature that enables users to save previously used shipping
    addresses so they can be used again.  Whether that feature---or any
    feature---is included on a site is a question of scope.

*** The Strategy Plane

    #+CINDEX:strategy plane
    #+CINDEX:plane, strategy
    The scope is fundamentally determined by the *strategy* of the site.  This
    strategy incorporates not only what the people running the site want to get
    out of it but what the users want to get out of the site as well.  In the
    case of our store example, some of the strategic objectives are pretty
    obvious---such as the the role that advertising or content produced by our
    users plays in our business model, for example---might not be so easy to
    articulate.

** Building From Bottom To Top

   These five planes:
   1. strategy
   2. scope
   3. structure
   4. skeleton
   5. surface


   #+CINDEX:framework, conceptual, user experience
   #+CINDEX:user experience conceptual framework
   #+CINDEX:tools
   {{{noindent}}}provide a conceptual framework for talking about user
   experience problems and the tools we use to solve them.

   {{{heading(Levels of Abstractness to Concretness)}}}

   #+CINDEX:abstractness
   #+CINDEX:concreteness
   On each plane, the issues we must deal with become a little less abstract
   and a little more concrete.  On the lowest plane, we are not concerned with
   the final shape of the site, product, or service at all---we only care about
   how the site will fit into our strategy (while meeting the needs of our
   users).  On the highest planem, we are only concerned with the most concrete
   details of the appearance of the product.  Plane by plane, the decisions we
   have to make become a little more specific and involve finer levels of
   detail.

   {{{heading(Interdependency Between Planes)}}}

   #+CINDEX:dependence between planes
   #+CINDEX:consequences of failure of dependence
   Each plane is dependent on the planes below it.  So, the surface depends on
   the skeleton which depends on the structure, whihc depends on the scope,
   which depends on the strategy.  When the choices we make don't align with
   those above and below, projects derail, deadlines are missed, and the costs
   begin to skyrocket as the development team tries to piece together
   components that don't naturally fit.  Even worse, when the product finally
   does launch, users often hate it, because it doesn't deliver a satisfying
   experience.  This dependence means that decisions on the strategy plane will
   have a sort of ``ripple effect'' all the way up the chain.  Conversely, the
   choices available to use on each plane are constrained by the decisions we
   make about issues on the planes below it.

   #+CINDEX:dependencies, both directions
   That does not mean, however, that every decision about a lower plane must be
   made before the plane above it can be addressed.  Dependencies run in both
   directions, with decisions made on upper planes sometimes forcing a
   reevaluation (or an evaluation made for the first time!) of issues on lower
   planes.  At each level, we make decisions according to what the competition
   is doing, industry best practices, what we know about our users, and plain
   old common sense.  These decisions can have a ripple effect in both
   directions.

   If you consider your decisions on lower planes to be set in stone before you
   take on your first decisions in higher planes, you will almost certainly be
   throwing your project schedule---and possible the success of your final
   product---into jeopardy.

   Instead, you should plan your project so that work on any plane cannot
   /finish/ before work on lower planes has finished.  The important
   consideration here is to not build the roof of the house before you know the
   shape of the foundation.

** A Basic Duality

   #+CINDEX:user experience, multiple terms
   #+CINDEX:interaction design
   #+CINDEX:information design
   #+CINDEX:information architecture
   Of course, there are more than just five elements of user experience, and as
   with any specialized field, this one has evolved a vocabulary all its own.
   To someone encountering the field for the first time, user experience can
   appear to be a complicated business.  All these seemingly identical terms
   are thrown around:
   - interaction design
   - information design
   - information architecture


   #+CINDEX:buzzwords
   {{{noindent}}}What do they mean?  Anything?  Or are they just more
   meaningless industry buzzwords?

   To further complicate matters, people will use the same terms in different
   ways.  One person might use ``information design'' to refer to what another
   knows as ``information architecture.''  And what's the difference between
   ``interface design'' and ``interaction design?''  Is there one?

   {{{heading(Evolution of the ``Web'')}}}

   #+CINDEX:Web, history
   #+CINDEX:information, the Web
   #+CINDEX:Berners-Lee, Tim
   When the Web started, it was all about information.  People could create
   documents, and they could link them to other documents.  Tim Berners-Lee,
   the inventor of the Web, created it as a way for researchers in the
   high-energy physics community, who were spread out all over the world, to
   share and refer to each other's findings.  He knew the Web had the potential
   to be much more than that, but few others really understood how great its
   potential was.

   #+CINDEX:Web, as publishing medium
   #+CINDEX:Web, new functionality
   #+CINDEX:Web, interactive
   People originally seized on the Web as a new publishing medium, but as
   technology advanced and new features were added to Web browsers and Web
   servers alike, the Web took on new functional capabilities.  After the Web
   began to catch on in the larger Internet community, it developed a more
   complex and robust feature set that would enable Web sites not only to
   distribute information but to collect and manipulate it as well.  With this,
   the Web became more interactive, responding to the input of users in ways
   that build upon and sometimes moved beyond traditional desktop applications.

   #+CINDEX:Web, commercial interests
   With the advent of commercial interests on the Web, this application
   functionality found a wide range of uses, such as electronic commerce,
   social media, and financial services, among others.  Meanwhile, the Web
   continued to flourish as a publishing medium, with countless newspapers and
   magazine sites augmenting the wave of Web-only blogs and ``e-zines'' being
   published.  Technology continued to advance on both fronts as all kinds of
   sites made the transition from static collections of information thtat
   changes infrequently to dynamic, database-driven sites that were constantly
   evolving.

   #+CINDEX:Web, user experience, formation, two languages
   #+CINDEX:application design problem
   #+CINDEX:problem-solving approaches, user experience
   #+CINDEX:information distribution and retrieval
   #+CINDEX:information science, user experience
   When the Web user experience community started to form, its members spoke
   two different languages.  One group saw every problem as an application
   design problem, and applied problem-solving approaches from the traditional
   desktop and mainframe software worlds.  (These, in turn, were rooted in
   common practices applied to creating all kinds of products, from cars to
   running shoes.)  The other group saw the Web in terms of information
   distribution and retrieval, and applied problem-solving approaches from the
   traditional worlds of publishing, media, and information science.

   #+CINDEX:stumbling block, failure of agreement, terminology
   #+CINDEX:terminology, stumbling block, failure of agreement
   #+CINDEX:web sites, hybrid between functional and informational
   #+CINDEX:hybrid web sites
   This became quite a stumbling block.  Very little progress could be made
   when the community could not even agree on basic terminology.  The waters
   were further muddied by the fact that most Web sites could not be neatly
   categorized as either functional applications or information resources---a
   huge numnber seemed to be a sort of hybrid, incorporating qualities from
   each world.

   {{{heading(Duality of Purpose: Funtional vs Informational)}}}

   #+CINDEX:duality, function vs information
   #+CINDEX:function vs information duality
   To address this basic duality in the nature of the Web, let's split our five
   planes down the middle.  On the left, we'll put those elements specific to
   the Web as a platform for *functionality*.  On the right, we'll put the
   elements specific to the Web as an *information medium*.

   #+NAME:tab:duality
   #+CAPTION:The Duality of Purpose: Function vs Information
   | product as functionality    | product as information     | quality  |
   |-----------------------------+----------------------------+----------|
   | SURFACE                     | SURFACE                    | Concrete |
   | - Sensory Design            | - Sensory Design           |          |
   | SKELETON                    | SKELETON                   | ...      |
   | - Information Design        | - Information Design       |          |
   | -- Interface Design         | -- Navigation Design       |          |
   | STRUCTURE                   | STRUCTURE                  | ...      |
   | - Interaction Design        | - Information Architecture |          |
   | SCOPE                       | SCOPE                      | ...      |
   | - Functional Specifications | - Content Requirements     |          |
   | STRATEGY                    | STRATEGY                   | ...      |
   | - User Needs                | - User Needs               |          |
   | - Product Objectives        | - Product Objectives       | Abstract |
   |-----------------------------+----------------------------+----------|

   {{{subheading(Functionality---Tasks)}}}

   #+CINDEX:tasks, functionality
   #+CINDEX:product as tool, task-oriented
   #+CINDEX:tools for task completion
   On the functionality side, we are mainly concerned with *tasks*---the steps
   involved in a process and how people think about completing them.  Here, we
   consider the product as a tool or set of tools that the user employs to
   accomplish one or more tasks.

   {{{subheading(Information Offered to Users)}}}

   #+CINDEX:product as information
   #+CINDEX:user experience, information-rich
   On the opposite side, our concern is what *information* the product offers
   and what it means to our users.  Creating an information-rich user
   experience is about enabling people to find, absorb, and make sense of the
   information we provide.

** The Elements of User Experience

   Now we can map that whole confusing array of terms into the model.  By
   breaking each plane down into its component elements, we will be able to
   take a closer look at how all the pieces fit together in the course of
   designing the whole user experience.

*** The Strategy Plane

    #+CINDEX:strategy plane
    #+CINDEX:plane, strategy
    #+CINDEX:user needs
    #+CINDEX:goals for site, from users
    The same strategic concerns come into play for both functionality-oriented
    products and information-oriented resources.  *User needs* are the goals
    for the site that come from outside our organization---specifically from
    the people who will use our site.  We must understand what our audience
    wants from us and how that fits in with other goals they have.

    #+CINDEX:product objectives
    #+CINDEX:goals for site, from owners
    Balanced against user needs are our own objectives for the site.  These
    *product objectives* can be business goals (``Make $1 million in sales over
    the Web this year'') or other kinds of goals (``Inform voters about the
    candidates in the next election'').  In Chapter 3 we will go into more
    detail about these elements.

*** The Scope Plane

    #+CINDEX:scope plane
    #+CINDEX:plane, scope
    #+CINDEX:functional specifications
    #+CINDEX:specifications, functional
    #+CINDEX:feature set
    #+CINDEX:content requirements, informational
    On the functionality side, the strategy is translated into scope through
    the creation of *functional specifications*: a detailed description of the
    ``feature set'' of the product.  On the information side, scope takes the
    form of *content requirements*: a description of the various elements that
    will be required.  Chapter 4 will cover the scope elements.

*** The Structure Plane

    #+CINDEX:structure plane
    #+CINDEX:plane, structure
    #+CINDEX:interaction design, functional
    #+CINDEX:behavior of system, defined
    #+CINDEX:information architecture
    #+CINDEX:architecture, information
    #+CINDEX:understanding, arrangent of content elements to facilitate
    The scope is given structure on the functionality side through *interaction
    design*, in which we define how the system behaves in response to the
    user.  For information resources, the structure is the *information
    architecture*: the arrangement of content elements to facilitate human
    understanding.  You'll find more details on these in Chapter 5.

*** The Skeleton Plane

    #+CINDEX:skeleton plane
    #+CINDEX:plane, skeleton
    #+CINDEX:information design
    #+CINDEX:interface design, functional
    #+CINDEX:functionality, interacting with
    #+CINDEX:navigation design, informational
    #+CINDEX:information architecture, moving through
    The skeleton plane breaks down into three components.  On both sides, we
    must address *information design*: the presentation of information in a way
    that facilitates understanding.  For functionality-oriented products, the
    skeleton also includes *interface design*, or arranging interface elements
    to enable users to interact with the functionality of the system.  The
    interface for an information resource is its *navigation design*: the set
    of screen elements that allow the user to move through the information
    architecture.  There's more about the skeleton plane in Chapter 6.

*** The Surface Plane

    #+CINDEX:surface plane
    #+CINDEX:plane, surface
    #+CINDEX:sensory experience
    #+CINDEX:finished product, user experience
    Finally we have the surface.  Regardless of whether we are dealing with a
    functionality-oriented product or an information resource, our concern here
    is the same: the *sensory experience* created by the finished product.
    It's trickier than it sounds; you can find out all about it in Chapter 7.

** Using the Elements

   #+CINDEX:user experience, difficulty identifying problems
   #+CINDEX:user experience model
   This model, divided up into neat boxes and planes, is a convenient way to
   think about user experience problems.  In reality, of course, the lines
   between these areas are not so clearly drawn.  Frequently, it can be
   difficult to identify whether a particular user experience problem is best
   solved through attention to one element instead of another.  Can a change to
   the visuals do the trick, or will the underlying navigation design have to
   be reworked?  Some problems require attention in several areas at once, and
   some seem to straddle the borders identified in this model.

   Few produces or services fall exclusively on one side of this model or the
   other.  Within each plane, the elements must work together to accomplish
   that plane's goals.  Separating the effects of decisions you make about one
   element from all other elements on the plane is difficult.  For example,
   information design, navigation design, and interface design jointly define
   the skeleton of a product.  All the elements on every plane have a common
   functionality in determining the larger user experience---in this case,
   defining the product's skeleton---even if they perform that function in
   different ways.

   #+CINDEX:responsibility for user experience, delegation
   The way organizations delegate responsibility for user experience issues
   often complicates matters further.  In some organizations, you will
   encounter people with job titles like /information architect/ or /interface
   designer/.  Don't be confused by this.  These people generally have
   expertise spanning many of the elements of user experience, not just the
   specialty indicated by their title.  It's not necessary to have a member of
   your team who is a specialist in each of these areas; instead, you only have
   to ensure that someone spends at least part of their time thinking about
   each of these issues.

   {{{heading(Content and Technology Affecting User Experience)}}}

   #+CINDEX:content
   A couple of additional factors go into shaping the final user experience
   that  you won't find covered in detail here.  The first is *content*.  The
   old saying (well, old in Web years) is that ``content is king'' on the Web.
   This is absolutely true---the single most important thing most Web sites can
   offer to their users is content that those users will find valuable.

   Users don't visit Web sites to experience the joy of navigation.  The
   content that is available to you (or that you have resources to obtain and
   manage) will play a huge role in shaping your site.  In the case of an
   online store, you might decide that you want the users to be able to see
   cover images of all the books you sell.  If you can get them, will you have
   a way to catalog them, keep track of them, and keep them up to date?  And
   what if you can't get photos of the book covers at all?  These content
   questions are essential to the ultimate user experience of the site.

   #+CINDEX:technology
   Second, *technology* can be just as important as content in creating a
   successful user experience.  In many cases, the nature of the experience you
   provide your users is largely determined by technology.  In the early days
   of the Web, the tools to connect Web sites to databases were fairly
   primitive and limited.  As the technology has advanced, however, databases
   have become more widely used to drive Web sites.  This in turn has enabled
   more and more sophisticated user experience approaches, such as dynamic
   navigation systems that change in response to the way users move through the
   site.  Technology is always changing, and the field of user experience
   always has to adapty to it.  Nevertheless, the fundamental elements of user
   experience remain the same.

   {{{heading(Elements Apply Universally)}}}

   Although the author developed the Elements model in the course of his work
   on Web sites, others have since applied it to a wide range of products and
   services.  If you work on the Web, everything in this book applies to you.
   If you work on other kinds of technology products, you will see strong
   parallels to familiar considerations.  Even if you work on products or
   services that have nothing to do with technology, you can map these concepts
   to your own processes.

   The rest of this book looks at these elements, plane by plane, in greater
   detail.  We'll take a closer look at some of the tools and techniques
   commonly used to address each element.  Along the way, we'll see how these
   elements come into play in products that aren't Web sites at all.  We'll see
   what the elements on each plane have in common, what makes each one
   different, and how they affect each other to help us create the total user
   experience.

* The Strategy Plane

  {{{heading(Product Objectives and User Needs)}}}

  - User Needs
  - Product Objectives

  The foundation of a successful user experience is a clearly articulted
  strategy.  Knowing both what we want the product to accomplish for our
  organization and what we want it to accomplish for our user informs the
  decisions we have to make about every aspect of the user experience.  But
  answering these simple questions can be trickier than it looks.

** Defining the Strategy

   The most common reason for the failure of a Web site is not technology.
   It's not user experience either.  Web sites most often fail because---before
   the first line of code was written the first pixel was pushed, or the first
   server was installed---nobody bothered to answer two very basic questions:

   - What do we want to get out of this product?
   - What do our users want to get out of it?


   #+NAME:tab:strategy
   #+CAPTION:Defining the Strategy: Product objectives and User needs
   | product as functionality | product as information |
   |--------------------------+------------------------|
   | STRATEGY                 |                        |
   | -User Needs              | -User Needs            |
   | -Product Objectives      | -Product Objectives    |
   |--------------------------+------------------------|

   By answering the first questions, we describe the *product objectives*
   coming from inside the organization.  The second question addresses *user
   needs*, objectives imposed on the product from outside.  Together, product
   objectives and user needs form the /strategy plane/, the foundation for
   every decision in our process as we design the user experience.  Yet,
   amazingly, many user experience projects do not begin with a clear, explicit
   understanding of the underlying strategy.

   The key word here is /explicit/.  The more clearly we can articulate exactly
   what we want, and exactly what others want from us, the more precisely we
   can adjust our choices to meet these goals.

** Product Objectives

   The first part of making our strategy explicit is examining our own
   objectives for the product or service.  Too often, product objectives exist
   only as an unspoken understanding among those building the product.  When
   that understanding remains unspoken, different people often have different
   ideas about what the product is supposed to accomplish.

*** Business Goals

    People commonly use terms like /business goals/ or /business drivers/ to
    describe the internal strategic objectives.  I'm going to use the term
    /product objectives/ because these other terms are both too narrow and too
    broad: too narrow because not every internal goal is a business goal (after
    all, not every organization has the same kinds of goals that businesses
    do), and too broad because our concern here really is to identify in the
    most specific terms possible what we expect the product itself to
    accomplish, regardless of the rest of our business activities.

    Most people start out describing objectives for their products in very
    general terms.  In the case of Web sites, they fundamentally serve one of
    two purposes: to make the company money or to save the company money.
    Sometimes its both.  But exactly how these sites are supposed to do that is
    not always clear.

    On the other hand, objectives that are too specific don't adequately
    describe the strategic concerns at issue.  For example, stating that one of
    your objectives is ``to provide users with a real-time text communications
    tool'' doesn't explain how such a tool helps advance the objectives of your
    organization, or how it helps meet the needs of your users.

    In trying to strike a balance between being too specific and being too
    general, we want to avoid jumping ahead to identify solutions when we don't
    yet fully understand the problems.  To create a successful user experience,
    we have to make sure that every decision we make is rooted in a firm
    understanding of its consequences.  Clearly defining the conditions for
    success---without defining the path to get there---assures that we don't
    get ahead of ourselves.

*** Brand Identity

    One essential consideration in formulating the objectives for any product
    is brand identity.  When most of us see the word /branding/, we think of
    things like logos, color palettes, and typography.  While these visual
    aspects of brand are important (we'll revisit them in more detail when we
    get to the surface plane in Chapter 7), the concept of brand extends far
    beyond the visual.  Brand identity---a set of conceptual associations or
    emotional reactions---is important because it's inescable.  In the minds of
    your users, an impression about your organization is inevitably created by
    their interactions with your product.

    You must choose whether that impression happens by accident or as a result
    of conscious choices you have made in designing your product.  Most
    organizations choose to exert some control over the perception of their
    brand, which is why communicating brand identity is a very common product
    objective.  Branding isn't just for commercial entities, either---every
    organization with a Web site, from nonprofit foundations to government
    agencies to individuals, creates an impression through user experience.  By
    codifying the specific qualities of that impression as an explicit
    objective, you increase your chances that it will lbe a positive
    impression.

*** Success Metrics

    An important part of understanding your objectives is understanding how you
    will know when you have reached them.

    {{{heading(Measuring Success)}}}

     These are known as *success metrics*: indicators we can track after the
     product has been launched to see whether it is meeting our own objectives
     and our users' needs.  Defining good success metrics not only influences
     decisions made over the course of the project; achieving them provides
     concrete evidence of the value of use experience efforts if you find
     yourself a skeptical audience when seeking budget approval for your next
     user experience project.

     Sometimes these metrics are related to the product itself and how it is
     used.  How much time does the average user spend on your site during each
     visit?  (Analytics tools can help you determine this.)  If you want to
     encourage your users to feel comfortable with the site, hang out, and
     explore what you have to offer, you'll want to see the times per visit
     increase.  On the other hand, if you want to provide quick, get-in-and-out
     access to information and functionality, you may want to decrease the time
     per visit.

     #+BEGIN_cartouche
     Success metrics are concrete indicators of how effectively the user
     experience is meeting strategic goals.  Measuring the number of visits per
     registered user per month indicates how valuable the site is to its core
     audience.
     #+END_cartouche

     For sites that depend on advertising revenue, impressions---the number of
     times each day an ad is served to a user---is an incredibly important
     metric.  But you have to be careful to balance your objectives and the
     needs of your users.  Adding several layers of navigational pages between
     the home and the content users want will definitely increase your ad
     impressions, but is it serving user needs?  Probably not.  And in the long
     run, it will show: As your users get frustrated and decide not to come
     back, your impressions will drop from that initial high and will probably
     end up lower than they were when you started.

     Not all sucess metrics have to be derived directly from your site.  You
     can measure the indirect effects of the site as well.  If your site
     provides solutions to common problems people encounter with your product,
     the number of phone calls coming into your customer support lines should
     go down.  An effective intranet can provide ready access to tools and
     resources that can cut down on the time it takes for your salespeople to
     close a sale---which, in turn, translates directly into increased revenue.

     For success metrics to meaningfully drive user experience decisions, those
     metrics must be clearly tied to aspects of user behavior that can be
     shaped by our design choices.

     The user experience of your site can't do much by itself to bring new
     users to your site---you'll have to rely upon word-of-mouth or your
     marketing efforts for that.  But the user experience has a whole lot of
     influence on whether those visitors come back.  Measuring return visits
     can be a great way to assess whether you're meeting user needs, but be
     careful: Sometimes those users don't come back because your competitor
     launched a gigantic advertising campaign or because your company just got
     some bad press.  Any metric viewed in isolation can be misleading; be sure
     to take a step back and look at what's going on beyond the Web site to
     make sure you're getting the whole story.

** User Needs

*** User Segmentation

*** Usability and User Research

**** Market research methods

**** Contextual inquiry

**** Task analysis

**** User testing

*** Creating Personas

** Team Roles and Process

* The Scope Plane
* The Structure Plane
* The Skeleton Plane
* The Surface Plane
* The Elements Applied
* INDEX
  :PROPERTIES:
  :INDEX:    cp
  :END:
* TABLES
  :PROPERTIES:
  :UNNUMBERED:
  :END:
  #+TEXINFO: @listoffloats Table
* COPYING
  :PROPERTIES:
  :COPYING:  t
  :END:
  @@texinfo:@b{@@The Elements of User Experience: User-Centered Design for the
  Web and Beyond@@texinfo:}@@

  \copy 2011 {{{AUTHOR}}}
* EXPORT SETTINGS                                                  :noexport:
#+TEXINFO_CLASS: info
#+TEXINFO_HEADER:
#+TEXINFO_POST_HEADER:
#+TEXINFO_DIR_CATEGORY: Web Development
#+TEXINFO_DIR_TITLE: Elements of User Experience
#+TEXINFO_DIR_DESC: User-Centered design for the web
* MACRO DEFINITIONS                                                :noexport:
  #+MACRO: heading @@texinfo:@heading $1@@
  #+MACRO: subheading @@texinfo:@subheading $1@@
  #+MACRO: noindent @@texinfo:@noindent @@
